#!/usr/bin/env python3
"""Generates app/src/main/java/ch/madtreasures/fluency/models/ModelFiles.kt

Every download URL is pinned to the Hugging Face commit that was current when this script ran,
so the SHA-256 values stay valid even if the repositories change later.
LFS files: SHA-256 from the Hub API. Small non-LFS files: downloaded and hashed here.

usage: python3 -I tools/gen_model_files.py
"""
import hashlib
import json
import os
import sys
import urllib.parse
import urllib.request

HF = "https://huggingface.co"

# model id -> (repo, [file paths or "dir/**"])
MODELS = {
    "hy-mt2-1.8b": ("tencent/Hy-MT2-1.8B-GGUF", ["Hy-MT2-1.8B-Q4_K_M.gguf"]),
    "milmmt-46-4b": ("mradermacher/MiLMMT-46-4B-v1.0-GGUF", ["MiLMMT-46-4B-v1.0.Q4_K_M.gguf"]),
    "milmmt-46-1b": ("mradermacher/MiLMMT-46-1B-v1.0-GGUF", ["MiLMMT-46-1B-v1.0.Q4_K_M.gguf"]),
    "parakeet-tdt-0.6b-v3": ("csukuangfj/sherpa-onnx-nemo-parakeet-tdt-0.6b-v3-int8",
                             ["encoder.int8.onnx", "decoder.int8.onnx", "joiner.int8.onnx", "tokens.txt"]),
    "whisper-turbo": ("csukuangfj/sherpa-onnx-whisper-turbo",
                      ["turbo-encoder.int8.onnx", "turbo-decoder.int8.onnx", "turbo-tokens.txt"]),
    "swiss-whisper-turbo": ("gariwat/swiss-german-whisper-ggml", ["ggml-model-q5_0.bin"]),
    "silero-vad": ("csukuangfj/vad", ["silero_vad_v5.onnx"]),
    "espeak-ng-data": ("csukuangfj/vits-piper-de_DE-thorsten-medium", ["espeak-ng-data/**"]),
    "piper-de-thorsten": ("csukuangfj/vits-piper-de_DE-thorsten-medium", ["de_DE-thorsten-medium.onnx", "tokens.txt"]),
    "piper-en-lessac": ("csukuangfj/vits-piper-en_US-lessac-medium", ["en_US-lessac-medium.onnx", "tokens.txt"]),
    "piper-fr-siwis": ("csukuangfj/vits-piper-fr_FR-siwis-medium", ["fr_FR-siwis-medium.onnx", "tokens.txt"]),
    "piper-it-paola": ("csukuangfj/vits-piper-it_IT-paola-medium", ["it_IT-paola-medium.onnx", "tokens.txt"]),
    "piper-es-davefx": ("csukuangfj/vits-piper-es_ES-davefx-medium", ["es_ES-davefx-medium.onnx", "tokens.txt"]),
    "piper-pt-tugao": ("csukuangfj/vits-piper-pt_PT-tugao-medium", ["pt_PT-tugao-medium.onnx", "tokens.txt"]),
}
EXTRA = json.loads(os.environ.get("FLUENCY_EXTRA_MODELS", "{}"))  # {"id": ["repo", [files]]}
MODELS.update({k: (v[0], v[1]) for k, v in EXTRA.items()})


def get_json(url):
    with urllib.request.urlopen(url, timeout=120) as r:
        return json.load(r)


def sha256_url(url):
    h = hashlib.sha256()
    n = 0
    with urllib.request.urlopen(url, timeout=300) as r:
        while True:
            b = r.read(1 << 20)
            if not b:
                break
            h.update(b)
            n += len(b)
    return h.hexdigest(), n


def tree(repo, rev, path=""):
    q = f"{HF}/api/models/{repo}/tree/{rev}"
    if path:
        q += "/" + urllib.parse.quote(path)
    return get_json(q + "?recursive=true")


def main():
    out = []
    for mid, (repo, wanted) in MODELS.items():
        info = get_json(f"{HF}/api/models/{repo}")
        rev = info["sha"]
        entries = {}
        for w in wanted:
            base = w[:-3] if w.endswith("/**") else os.path.dirname(w)
            for e in tree(repo, rev, base):
                if e["type"] == "file":
                    entries[e["path"]] = e
        files = []
        for w in wanted:
            paths = sorted(p for p in entries if p.startswith(w[:-2])) if w.endswith("/**") else [w]
            for p in paths:
                e = entries[p]
                url = f"{HF}/{repo}/resolve/{rev}/{urllib.parse.quote(p)}"
                lfs = e.get("lfs")
                if lfs:
                    sha, size = lfs["oid"], lfs["size"]
                else:
                    sha, size = sha256_url(url)
                    assert size == e["size"], (p, size, e["size"])
                files.append((url, p, size, sha))
        total = sum(f[2] for f in files)
        print(f"{mid:24s} {repo}@{rev[:10]} {len(files):4d} files {total/1e6:9.1f} MB", file=sys.stderr)
        out.append((mid, files))

    lines = [
        "// GENERATED by tools/gen_model_files.py - do not edit by hand.",
        "// Download URLs are pinned to Hugging Face commits; size and SHA-256 are verified after download.",
        "package ch.madtreasures.fluency.models",
        "",
        "internal object ModelFiles {",
        "    /** model id -> files as \"url|relativePath|size|sha256\" */",
        "    private val raw: Map<String, List<String>> = mapOf(",
    ]
    for mid, files in out:
        lines.append(f'        "{mid}" to listOf(')
        for url, p, size, sha in files:
            lines.append(f'            "{url}|{p}|{size}|{sha}",')
        lines.append("        ),")
    lines += [
        "    )",
        "",
        "    fun forModel(id: String): List<RemoteFile> = raw[id].orEmpty().map { line ->",
        "        val (url, path, size, sha) = line.split('|')",
        "        RemoteFile(url = url, path = path, size = size.toLong(), sha256 = sha)",
        "    }",
        "",
        "    val ids: Set<String> get() = raw.keys",
        "}",
        "",
    ]
    dst = os.path.join(os.path.dirname(__file__), "..", "app", "src", "main", "java", "ch", "madtreasures",
                       "fluency", "models", "ModelFiles.kt")
    os.makedirs(os.path.dirname(dst), exist_ok=True)
    with open(dst, "w") as f:
        f.write("\n".join(lines))
    print("wrote", os.path.normpath(dst), file=sys.stderr)


if __name__ == "__main__":
    main()
